# Generated by Django 5.2.7 on 2025-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_name_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=0, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
