# Generated by Django 5.2.7 on 2025-11-14 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("course_name", models.CharField(max_length=255)),
                ("course_code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("credit", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Prof",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("prof_name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("imgurl", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Enrollments",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("section_number", models.CharField(max_length=50)),
                ("datetime", models.CharField(blank=True, max_length=255)),
                ("room", models.CharField(blank=True, max_length=100)),
                (
                    "campus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sections",
                        to="core.campus",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.course",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="enrolled_sections",
                        through="core.Enrollment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="enrollment",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.section"
            ),
        ),
        migrations.CreateModel(
            name="Teach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prof",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.prof"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.section"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Teaching Assignments",
                "unique_together": {("prof", "section")},
            },
        ),
        migrations.AddField(
            model_name="section",
            name="teachers",
            field=models.ManyToManyField(
                related_name="teaching_sections", through="core.Teach", to="core.prof"
            ),
        ),
        migrations.CreateModel(
            name="SectionTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.section"
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.timeslot"
                    ),
                ),
            ],
            options={
                "unique_together": {("section", "slot")},
            },
        ),
        migrations.AddField(
            model_name="section",
            name="schedule",
            field=models.ManyToManyField(
                related_name="scheduled_sections",
                through="core.SectionTime",
                to="core.timeslot",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("user", "section")},
        ),
    ]
