# Generated by Django 5.2.7 on 2025-12-12 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSearchStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("count", models.IntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_stats",
                        to="core.course",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="core_course_date_55352d_idx"),
                    models.Index(
                        fields=["course"], name="core_course_course__05f920_idx"
                    ),
                ],
                "unique_together": {("course", "date")},
            },
        ),
        migrations.CreateModel(
            name="DailyActiveUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_active_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="core_dailya_date_8a8a70_idx")
                ],
                "unique_together": {("user", "date")},
            },
        ),
    ]
