# Generated by Django 5.2.7 on 2025-11-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="section_number",
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
