# Generated by Django 5.2.7 on 2025-11-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_section_section_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section_number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='campus',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='professor',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
