# Generated by Django 5.2.7 on 2025-12-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_coursesearchstat_dailyactiveuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseReviewStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("count", models.IntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_stats",
                        to="core.course",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="core_course_date_f5f01a_idx"),
                    models.Index(
                        fields=["course"], name="core_course_course__54ce9c_idx"
                    ),
                ],
                "unique_together": {("course", "date")},
            },
        ),
        migrations.CreateModel(
            name="CourseViewStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("count", models.IntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_stats",
                        to="core.course",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="core_course_date_4f0ba4_idx"),
                    models.Index(
                        fields=["course"], name="core_course_course__775aa3_idx"
                    ),
                ],
                "unique_together": {("course", "date")},
            },
        ),
    ]
