# Generated by Django 5.2.7 on 2025-11-09 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_section_number_section_number_campus_img_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='contact',
            new_name='email',
        ),
        migrations.AddField(
            model_name='professor',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.roommsteam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
