# Generated by Django 5.2.7 on 2025-12-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coursereviewstat_courseviewstat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursesearchstat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coursesearchstat',
            name='course',
        ),
        migrations.AlterUniqueTogether(
            name='courseviewstat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='courseviewstat',
            name='course',
        ),
        migrations.AlterUniqueTogether(
            name='dailyactiveuser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailyactiveuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='CourseReviewStat',
        ),
        migrations.DeleteModel(
            name='CourseSearchStat',
        ),
        migrations.DeleteModel(
            name='CourseViewStat',
        ),
        migrations.DeleteModel(
            name='DailyActiveUser',
        ),
    ]
