# Generated by Django 5.2.7 on 2025-11-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_contact_professor_email_professor_room_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="number",
            new_name="section_number",
        ),
    ]
