# Generated by Django 5.2.7 on 2025-11-14 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("review", "0002_alter_reviewvote_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="prof",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="core.prof",
            ),
        ),
    ]
